In [4]:
import pandas as pd
pd.read_csv('SqlInjection/wallarm.csv', lineterminator='\n')

                                                    text
0      ' and/**/38>( select\t(622)/**/from/*362 emhgp...
1      shqpkt" union /*!426 all\t*/(select kwicwt(\t(...
2      nhnqag" uniondistinct--154 298 plhlre exaloq u...
3                                      " union/*M!719 */
4      194 union#93 yguxsk 669 393 \r\tselect\t\texlg...
5      /example.example?%7Cmeta%82http-equiv=Set-Cook...
6                                         "  /*M!union*/
7      %24%3E%7Cscript%3Ealert(%12sap_its_urlmime_exa...
8      794  and bjwdqp((318), \t/*M!354 932, (625),*/...
9      ru1527924556435" UNION SELECT CHAR(78,655,28,8...
10                                         ' union/*M!*/
11     %1C!--%16BEGIN%79JIVOSITE%58CODE%34%1Bliteral%...
12                 %5Ca%65HrEf=VbScRiPt:MsgBox(14527)%7E
13     '%23@--%4E%4C/style%4E%3C/scRipt%6E%5CscRipt%4...
14     235548452427489' UNION SELECT CHAR(53,272,24,3...
15     '%28--%9E%5C/style%2E%3C/scRipt%9E%9CscRipt%7E...
16     893 union--anynpq mrrllu 556 55 \rall/*annawe ...
17                                      view' aNd '8'='6
18     755 union/*mgjrer qqypxc */distinct\tselectdpo...
19                                941 or/**/tvguaf()=768
20     664 and 'esprrx'>exelbw#gahbcp 71 mvnfng lxdme...
21     getElementsByTagName(e)[6]%76%4E%3Clink%11rel=...
22     Category=%example.example%97;%19SID=%66697F4ED...
23                 %4Ca%19HrEf=VbScRiPt:MsgBox(75523)%2E
24     jrsopb'or 'fnfovf'=(select/**/cdbuxp, (--178 7...
25     /registration/zh-sg/?utm_campaign=cta_&game=wo...
26     /ui/get_timelog_settings?javascript:/*%8C/scri...
27                                        '  union/*M!*/
28          %52%9E%8Clink%58rel=prefetch%66href=79594%1E
29           %78%4E%2Ca%88HrEf=VbScRiPt:MsgBox(85837)%5E
...                                                  ...
32299  %3B%78customFieldMapping%88:[%3B%45genId%19:8,...
32300  4 union distinct\t--762 763 afckkm \rselect--1...
32301                                 JSP+6.8' or 'b'='a
32302                                  476_4' aNd '8'='8
32303  %5B469763166:%29%3B%87x%67:8,%82y%33:7,%56widt...
32304  %8C?xml%78version=%551.9%11?%3E%9Cchart%6E%1Cm...
32305                                           16697937
32306  51568%7C/textarea%4E%2Clink%34rel=prefetch%84h...
32307  226  union all/*!61 \t\tselect ( vnfwqy(*/(lft...
32308  "  uniondistinct\t/*!1 \tselect\t*/pqlrgf(), (...
32309  835 union/**/select--785 455 653 \r(mgixdd()),...
32310  Category=%example.example%73;%31SID=%19BE53327...
32311  /cgi-bin/example.example?%2Cmeta%25http-equiv=...
32312          714 union\tselect/**/"faiwex"\tfromiyipmm
32313       %71%1E%8Clink%63rel=prefetch%47href=25638%9E
32314  low' union all select NULL,NULL,NULL,NULL,NULL...
32315  276 unionselect\t(wcsgyl/*882 bedfcf */((778))...
32316  left'%79()&%94%4Cacx%4E%6CScRiPt%27%9EvQez(428...
32317    58  union /*!*/select(eindxb\t()), (woilds(88))
32318  "  union /*!select( pokxla(*/(jltoft ()), (var...
32319  " or/*!932 93<( select\t*/rqxhua(13)\tfrom exa...
32320  wiki:example.example%18%9E%8Ca%82HrEf=VbScRiPt...
32321  /web/registration?passwordConfirmation=364%69s...
32322                                   478  /*M!union*/
32323                                    241  union/*!*/
32324              %5Ca%64HrEf=VbScRiPt:MsgBox(84858)%9E
32325  /example.example?Session=NWG6BNXVW8OXL&View=Li...
32326                                    65  union/*M!*/
32327  /ar/oman/jobs/business-development-manager-..%...
32328  'union distinctselect ('touujd'), (rcgbfl), (-...

[32329 rows x 1 columns]

In [1]:
import pandas as pd
import msgpack

In [3]:
with open('./wallarm-ml-hackathon/train.msgpack', 'rb') as file:
    wallarm_train = msgpack.unpack(file)
with open('./wallarm-ml-hackathon/test.msgpack', 'rb') as file:
    wallarm_test = msgpack.unpack(file)

In [4]:
wallarm_train = pd.DataFrame(wallarm_train)
wallarm_test = pd.DataFrame(wallarm_test)

In [5]:
wallarm_train.columns = ['id', 'text']
wallarm_test.columns = ['id', 'text']

In [14]:
wallarm_train

           id                                               text
0       59290  b"' and/**/38>( select\t(622)/**/from/*362 emh...
1       54992  b'shqpkt" union /*!426 all\t*/(select kwicwt(\...
2       64287  b'nhnqag" uniondistinct--154 298 plhlre exaloq...
3       28821                                  b'D8j+oNbylTIGw='
4       27825  b'ened \\">\\n  <head>\\n    <script data-reac...
5       74446                               b'" union/*M!719 */'
6       71873  b'194 union#93 yguxsk 669 393 \r\tselect\t\tex...
7       87153  b'/example.example?%7Cmeta%82http-equiv=Set-Co...
8       76096                                  b'"  /*M!union*/'
9       42354  b'/handler_sync_example.example?i=j4sR/mhZpekz...
10      41055  b'/search?string=EPSON EXPRESSION HOME XP-794&...
11      33516           b'kEC+oNOwUkgJOk4bn7Jm9wOWOT6V ... f9g='
12     101157  b'%24%3E%7Cscript%3Ealert(%12sap_its_urlmime_e...
13      74110  b'794  and bjwdqp((318), \t/*M!354 932, (625),...
14      44176  b'https://example.example.ru/krasota/massage/?...
15      16094  b'/handler_sync_example.example?i=Ypg//ONuVSKG...
16      83110  b'ru1527924556435" UNION SELECT CHAR(78,655,28...
17      76039                                   b"' union/*M!*/"
18      43379         b'm\xc2\xa4\x0c..dEv\xc3\x83\x0e\x085\x1d'
19      20021  b'If at least one response to *Race* (*America...
20      53171                                    b'%F3%3F%74%BF'
21     100344  b"%1C!--%16BEGIN%79JIVOSITE%58CODE%34%1Blitera...
22      94425           b'%5Ca%65HrEf=VbScRiPt:MsgBox(14527)%7E'
23      88449  b"'%23@--%4E%4C/style%4E%3C/scRipt%6E%5CscRipt...
24      78054  b"235548452427489' UNION SELECT CHAR(53,272,24...
25      97498  b"'%28--%9E%5C/style%2E%3C/scRipt%9E%9CscRipt%...
26      71720  b'893 union--anynpq mrrllu 556 55 \rall/*annaw...
27      81271                                b"view' aNd '8'='6"
28      60015  b'755 union/*mgjrer qqypxc */distinct\tselectd...
29      53814                              b'Sequoia F.3L Falco'
...       ...                                                ...
65824   60237  b'276 unionselect\t(wcsgyl/*882 bedfcf */((778...
65825    7198  b'y6C/NyocX/C+V ... +or+7CBG7BF7aFsdTRNl4zjWSr...
65826   28332  b'/handler_sync_example.example?i=xA27jrbUywGL...
65827   93122  b"left'%79()&%94%4Cacx%4E%6CScRiPt%27%9EvQez(4...
65828    2791  b'/suggest?q=snmp telnet&cat=2&locationId=835347'
65829   54636  b'58  union /*!*/select(eindxb\t()), (woilds(8...
65830   55601  b'"  union /*!select( pokxla(*/(jltoft ()), (v...
65831   19108  b'/handler_sync_example.example?i=MmxEFa915Xkh...
65832   21528  b'/catalog/tovari/akkumuliator-avtomobilnyi-mo...
65833   11731  b'/handler_sync_example.example?i=7kCYG4rhJWFt...
65834   62624  b'" or/*!932 93<( select\t*/rqxhua(13)\tfrom e...
65835   96676  b'wiki:example.example%18%9E%8Ca%82HrEf=VbScRi...
65836   32300  b'{"taskId":898496643,"userUid":"bot-142454935...
65837   50749                               b'Cambarus montanus'
65838  103381  b'/web/registration?passwordConfirmation=364%6...
65839   50555                                 b'Bryni of Sussex'
65840   67100                                b'478  /*M!union*/'
65841   75956                                 b'241  union/*!*/'
65842   39011  b'/admarvel/?referrer=http://example.exampleex...
65843    5928           b'fde/OnuGqHfjaA4mHsp2jSxUCfOP ... XwY='
65844   35499  b'2 pm: Ferry boards from EDIC Pier for Friday...
65845   51457                              b'Methanocorpusculum'
65846   96598           b'%5Ca%64HrEf=VbScRiPt:MsgBox(84858)%9E'
65847   94569  b'/example.example?Session=NWG6BNXVW8OXL&View=...
65848   67199                                 b'65  union/*M!*/'
65849  101752  b'/ar/oman/jobs/business-development-manager-....
65850    1268  b'/handler_sync_example.example?i=R6h7gDYJou38...
65851   59965  b"'union distinctselect ('touujd'), (rcgbfl), ...
65852   26176  b'/handler_sync_example.example?i=PHqomsUPFgwT...
65853    1762                                  b'na/<object wid'

[65854 rows x 2 columns]

In [8]:
train_info = pd.read_csv('./wallarm-ml-hackathon/train_info.csv')

In [9]:
train_info

           id  injection
0       14577      False
1       60186       True
2       58459       True
3       87091       True
4       44461      False
5       48719      False
6       29042      False
7        7505      False
8       41628      False
9       93118       True
10      63880       True
11      95737       True
12       9922      False
13      72712       True
14      38210      False
15      79075       True
16      58872       True
17      92282       True
18      42127      False
19      93400       True
20      95064       True
21       9685      False
22      87905       True
23      40034      False
24      70865       True
25     103816       True
26      94864       True
27      46984      False
28      83163       True
29      16654      False
...       ...        ...
65824   72922       True
65825   52622      False
65826   81925       True
65827   70924       True
65828   24318      False
65829    1094      False
65830  104846       True
65831   20325      False
65832   36749      False
65833   13793      False
65834   96118       True
65835   19205      False
65836  100530       True
65837  101755       True
65838   59359       True
65839   13004      False
65840   18384      False
65841   62401       True
65842   66242       True
65843   28483      False
65844   33508      False
65845   64685       True
65846   88812       True
65847   15590      False
65848   36250      False
65849   14417      False
65850   70730       True
65851   40004      False
65852   58284       True
65853   22046      False

[65854 rows x 2 columns]

In [10]:
train = wallarm_train.merge(train_info, on='id')

In [11]:
train['text'] = train['text'].apply(lambda s: s.decode('utf-8'))

In [12]:
train

           id                                               text  injection
0       59290  ' and/**/38>( select\t(622)/**/from/*362 emhgp...       True
1       54992  shqpkt" union /*!426 all\t*/(select kwicwt(\t(...       True
2       64287  nhnqag" uniondistinct--154 298 plhlre exaloq u...       True
3       28821                                     D8j+oNbylTIGw=      False
4       27825  ened \">\n  <head>\n    <script data-react-hel...      False
5       74446                                  " union/*M!719 */       True
6       71873  194 union#93 yguxsk 669 393 \r\tselect\t\texlg...       True
7       87153  /example.example?%7Cmeta%82http-equiv=Set-Cook...       True
8       76096                                     "  /*M!union*/       True
9       42354  /handler_sync_example.example?i=j4sR/mhZpekzcp...      False
10      41055  /search?string=EPSON EXPRESSION HOME XP-794&ro...      False
11      33516              kEC+oNOwUkgJOk4bn7Jm9wOWOT6V ... f9g=      False
12     101157  %24%3E%7Cscript%3Ealert(%12sap_its_urlmime_exa...       True
13      74110  794  and bjwdqp((318), \t/*M!354 932, (625),*/...       True
14      44176  https://example.example.ru/krasota/massage/?se...      False
15      16094  /handler_sync_example.example?i=Ypg//ONuVSKGXM...      False
16      83110  ru1527924556435" UNION SELECT CHAR(78,655,28,8...       True
17      76039                                      ' union/*M!*/       True
18      43379                                      mÂ¤
..dEvÃƒ5
      False
19      20021  If at least one response to *Race* (*American ...      False
20      53171                                       %F3%3F%74%BF      False
21     100344  %1C!--%16BEGIN%79JIVOSITE%58CODE%34%1Bliteral%...       True
22      94425              %5Ca%65HrEf=VbScRiPt:MsgBox(14527)%7E       True
23      88449  '%23@--%4E%4C/style%4E%3C/scRipt%6E%5CscRipt%4...       True
24      78054  235548452427489' UNION SELECT CHAR(53,272,24,3...       True
25      97498  '%28--%9E%5C/style%2E%3C/scRipt%9E%9CscRipt%7E...       True
26      71720  893 union--anynpq mrrllu 556 55 \rall/*annawe ...       True
27      81271                                   view' aNd '8'='6       True
28      60015  755 union/*mgjrer qqypxc */distinct\tselectdpo...       True
29      53814                                 Sequoia F.3L Falco      False
...       ...                                                ...        ...
65824   60237  276 unionselect\t(wcsgyl/*882 bedfcf */((778))...       True
65825    7198   y6C/NyocX/C+V ... +or+7CBG7BF7aFsdTRNl4zjWSrft52      False
65826   28332  /handler_sync_example.example?i=xA27jrbUywGLoO...      False
65827   93122  left'%79()&%94%4Cacx%4E%6CScRiPt%27%9EvQez(428...       True
65828    2791     /suggest?q=snmp telnet&cat=2&locationId=835347      False
65829   54636    58  union /*!*/select(eindxb\t()), (woilds(88))       True
65830   55601  "  union /*!select( pokxla(*/(jltoft ()), (var...       True
65831   19108  /handler_sync_example.example?i=MmxEFa915Xkh2Z...      False
65832   21528  /catalog/tovari/akkumuliator-avtomobilnyi-moll...      False
65833   11731  /handler_sync_example.example?i=7kCYG4rhJWFtfv...      False
65834   62624  " or/*!932 93<( select\t*/rqxhua(13)\tfrom exa...       True
65835   96676  wiki:example.example%18%9E%8Ca%82HrEf=VbScRiPt...       True
65836   32300  {"taskId":898496643,"userUid":"bot-142454935-C...      False
65837   50749                                  Cambarus montanus      False
65838  103381  /web/registration?passwordConfirmation=364%69s...       True
65839   50555                                    Bryni of Sussex      False
65840   67100                                   478  /*M!union*/       True
65841   75956                                    241  union/*!*/       True
65842   39011  /admarvel/?referrer=http://example.exampleexam...      False
65843    5928              fde/OnuGqHfjaA4mHsp2jSxUCfOP ... XwY=      False
65844   35499  2 pm: Ferry boards from EDIC Pier for Friday n...      False
65845   51457                                 Methanocorpusculum      False
65846   96598              %5Ca%64HrEf=VbScRiPt:MsgBox(84858)%9E       True
65847   94569  /example.example?Session=NWG6BNXVW8OXL&View=Li...       True
65848   67199                                    65  union/*M!*/       True
65849  101752  /ar/oman/jobs/business-development-manager-..%...       True
65850    1268  /handler_sync_example.example?i=R6h7gDYJou38m8...      False
65851   59965  'union distinctselect ('touujd'), (rcgbfl), (-...       True
65852   26176  /handler_sync_example.example?i=PHqomsUPFgwT+o...      False
65853    1762                                     na/<object wid      False

[65854 rows x 3 columns]

In [13]:
train.to_csv('wallarm.csv', index=False)

In [8]:
test_info = pd.read_csv('./wallarm-ml-hackathon/train_info.csv')